var gpxs = ["./routes/Deventer.gpx",
		"./routes/Goeree-Overflakkee.gpx",
		"./routes/Lekdijk.gpx",
		"./routes/Maasvlakte.gpx",
		"./routes/Noord-Beveland.gpx",
		"./routes/Schouwen_Duiveland.gpx",
		"./routes/Slot Loevestein.gpx",
		"./routes/Vuurtoren Ouddorp.gpx",
		"./routes/Brouwersdam.gpx",
		"./routes/Zuid-Hollandse Kust 2.gpx",
		"./routes/Belgische Kust.gpx",
		"./routes/Zuid-Beveland.gpx",
		"./routes/Zuid-Hollandse Kust 1.gpx",
		"./routes/Groene Hart 1.gpx",
		"./routes/Zuid-Beveland en Walcheren.gpx",
		"./routes/Goudswaard en Nieuw-Beijerland.gpx",
		]